sudo: required

services:
    -docker

before_install:
    - docker build -t lidongdong559/react-test -f ./client/Dockerfile.dev ./client

script:
    # Run test
    - docker run lidongdong559/react-test npm test -- --coverage

after_success:
    - docker build -t lidongdong559/multi-client ./client
    - docker build -t lidongdong559/multi-nginx ./nginx
    - docker build -t lidongdong559/multi-server ./server
    - docker build -t lidongdong559/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push lidongdong559/multi-client
    - docker push lidongdong559/multi-nginx
    - docker push lidongdong559/multi-server
    - docker push lidongdong559/multi-worker
